more cleanup

diff --git a/nodecontroller/configure b/nodecontroller/configure
--- a/nodecontroller/configure
+++ b/nodecontroller/configure
@@ -5,6 +5,21 @@ set -x
 
 #This is configures an odroid to be a node controller
 
+export waggled_dir="$(pwd)/nc-wag-os/waggled"
+
+
+# Create symlink if repository is not already at the expected location
+if [ `pwd` != "/usr/lib/waggle/nodecontroller" ] ; then
+  mkdir -p /usr/lib/waggle/
+  if [ -d /usr/lib/waggle/nodecontroller ] && [ ! -L /usr/lib/waggle/nodecontroller ] ; then 
+    echo "Error: Directory /usr/lib/waggle/nodecontroller already exists."
+    exit 1
+  fi
+  ln -sf `pwd` /usr/lib/waggle/nodecontroller
+fi
+
+
+
 #install all dependencies for node
 #dpkg -i nc-wag-os/packages/debian/*.deb
 cd nc-wag-os/packages/python/
@@ -47,43 +62,49 @@ echo $server_ip > /etc/waggle/server_ip
 #move communications.sh into the init.d folder and update
 #starts communication processes
 #cd ./waggle/nodecontroller/nc-wag-os/waggled
-export waggled_dir="./nc-wag-os/waggled"
 
-cp ${waggled_dir}/communications.sh /etc/init.d
+#cp ${waggled_dir}/communications.sh /etc/init.d
+ln -sf  ${waggled_dir}/communications.sh /etc/init.d/
 #chmod +x /etc/init.d/communications.sh 
 update-rc.d communications.sh defaults 
 
 #move data_cache.sh into the init.d folder and update
 #starts data cache process
-cp ${waggled_dir}/data_cache.sh /etc/init.d
+#cp ${waggled_dir}/data_cache.sh /etc/init.d
+ln -sf  ${waggled_dir}/data_cache.sh /etc/init.d/
 #chmod +x /etc/init.d/data_cache.sh 
 update-rc.d data_cache.sh defaults 
 
 #comment this out if nodecontroller and guestnode are separate machines
 #move sensor.sh into the init.d folder and update
 #starts sensor script
-cp ${waggled_dir}/start_sensor.sh /etc/init.d
+#cp ${waggled_dir}/start_sensor.sh /etc/init.d
+ln -sf  ${waggled_dir}/start_sensor.sh /etc/init.d/
 #chmod +x /etc/init.d/start_sensor.sh 
 update-rc.d start_sensor.sh defaults 
 
 #set up SysMon stuff
 #starts WagMan script at boot
-cp ${waggled_dir}/WagMan_start.sh /etc/init.d
+#cp ${waggled_dir}/WagMan_start.sh /etc/init.d
+ln -sf  ${waggled_dir}/WagMan_start.sh /etc/init.d/
 #chmod +x /etc/init.d/WagMan_start.sh 
 update-rc.d WagMan_start.sh defaults 
 
 #starts set-up for heart beat script at boot
-cp ${waggled_dir}/heartbeat_setup_start.sh /etc/init.d
+#cp ${waggled_dir}/heartbeat_setup_start.sh /etc/init.d
+ln -sf  ${waggled_dir}/heartbeat_setup_start.sh /etc/init.d/
 #chmod +x /etc/init.d/heartbeat_setup_start.sh 
 #update-rc.d heartbeat_setup_start.sh defaults 
 
 #starts node controller heart beat at boot
-cp ${waggled_dir}/heartbeat_start.sh /etc/init.d
+#cp ${waggled_dir}/heartbeat_start.sh /etc/init.d
+ln -sf  ${waggled_dir}/heartbeat_start.sh /etc/init.d/
 #chmod +x /etc/init.d/heartbeat_start.sh 
 #update-rc.d heartbeat_start.sh defaults 
 
 #creates udev rule to attach SysMon to /dev/arduinoMicro
-cp ${waggled_dir}/99-usb-serial.rules /etc/udev/rules.d
+#cp ${waggled_dir}/99-usb-serial.rules /etc/udev/rules.d
+ln -sf  ${waggled_dir}/99-usb-serial.rules /etc/udev/rules.d/
 
 #find and set IP address if possible
 cd ${waggled_dir}/
