check cassandra version

diff --git a/server/configure b/server/configure
--- a/server/configure
+++ b/server/configure
@@ -7,6 +7,8 @@ set -e
 # Install all of the dependencies that the Waggle server needs
 # Get the IP for the cassandra node you want to send data to.
 
+source ./requirements.sh 
+
 if [ ${CASSANDRA_SERVER}x == "x" ] ; then
   read -p "Enter the IP address or hostname of the Cassandra server you want to use: " c_ip
 else
@@ -48,6 +50,16 @@ if [ $(./cqlsh.py ${c_ip} -e "quit;" > /dev/null 2>&1 ; echo $? ) != 0 ] ; then
   echo "error: could not connect to cassandra using address ${c_ip}."
   exit 1
 fi
+
+if [ ${REQUIRED_CASSANDRA_VERSION}x -ne "x" ] ; then
+  export GOT_CASS_VERSION=$(./cqlsh.py cassandra -e "SELECT release_version FROM system.local" | grep -o "[0-9.]\{3,7\}")
+  if [ ${REQUIRED_CASSANDRA_VERSION}x -ne ${GOT_CASS_VERSION}x ] ; then
+    echo "error: Cassandra version ${REQUIRED_CASSANDRA_VERSION} is required. Found ${GOT_CASS_VERSION}."
+    exit 1
+  fi
+fi
+
+
 
 # check if tables already exist, otherwise create them
 export GREP_TABLES=$(./cqlsh.py cassandra -e "use waggle; describe tables;" | grep "node_info" | grep "sensor_data" | wc -l)
